name: Terraform AWS Deployment

on:
  push:
    branches:
      - "feature/*"
      - "develop"

permissions:
  contents: read

jobs:
  terraform-feature:
    if: startsWith(github.ref, 'refs/heads/feature/')
    name: Terraform Plan (Feature Branch)
    runs-on: ubuntu-latest

    steps:
      - name: ğŸš€ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3

      - name: ğŸ”‘ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ğŸ“Œ Terraform Init
        run: terraform init

      - name: âœ… Terraform Validate
        run: terraform validate

      - name: ğŸ“‹ Terraform Plan
        run: terraform plan -out=tfplan

  terraform-develop:
    if: github.ref == 'refs/heads/develop'
    name: Terraform Apply (Develop Branch)
    runs-on: ubuntu-latest

    steps:
      - name: ğŸš€ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3

      - name: ğŸ”‘ configuracion de credenciales
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ğŸ“Œ Terraform Init
        run: terraform init

        

      - name: ğŸš€ Terraform Apply
        run: terraform apply -auto-approve
